### ISSUE TITLE
Include ether volatility as well

### ISSUE THREAD

**Issue by mecampbellsoup** [elidourado/btcvol#5]
Since ether is becoming the leading 'alternative' cryptocurrency, it might be reasonable to include its volatility figures as well. What do you think @elidourado?

**Comment by mecampbellsoup** [comment]
Correction: just ether, not gas. I realized I never knew what 'gas' really was but after just looking it up, it's not what we want 😝

**Comment by elidourado** [comment]
👍 on including ether. First thing we need is a pricing source. Criteria:

1. Historical daily data
2. Accurate, best measure
3. Likely to be around a while
4. Accessible through an API
5. Denominated in USD

For bitcoin, we use CoinDesk's [Bitcoin Price Index](http://www.coindesk.com/price/). Ideally, they would start tracking ether. But in the meantime, is there another source that meets the criteria?

**Comment by mecampbellsoup** [comment]
Maybe this?
https://www.etherchain.org/documentation/api/#api-Statistics-GetStatisticsPrice

Will keep poking around.

On May 29, 2016 at 11:20:43 AM, Eli Dourado (notifications@github.com)
wrote:

👍 on including ether. First thing we need is a pricing source. Criteria:

   1. Historical daily data
   2. Accurate, best measure
   3. Likely to be around a while
   4. Accessible through an API
   5. Denominated in USD

For bitcoin, we use CoinDesk's Bitcoin Price Index
<http://www.coindesk.com/price/>. Ideally, they would start tracking ether.
But in the meantime, is there another source that meets the criteria?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/elidourado/btcvol/issues/5#issuecomment-222366059>, or mute
the thread
<https://github.com/notifications/unsubscribe/AB8vraWtpfwOXXef9x4ZfyXC6ZtFtIShks5qGa7LgaJpZM4IpTws>
.

**Comment by elidourado** [comment]
OK, implemented ether volatility using the etherchain data. Since they have approximately hourly data, I just used the first datapoint in each day as the day's data. We should still look to see if there are better data sources, but in the meantime I am closing this.

Commit: https://github.com/elidourado/btcvol/commit/ca78b23923e315d95444bc5d6ea1a9b6ca157d18
